<a href="https://colab.research.google.com/github/atlas-github/nih_time_series_nlp/blob/main/concat_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#install the gdown library
!pip install gdown

In [ ]:
#download dengue csv
import pandas as pd
import gdown

# insert file_id
file_id1 = '1F-faNnQoyhdjbuyEVZPHV1cv_h0h5UDl'
url1 = f'https://drive.google.com/uc?id={file_id1}'

# Download the CSV file
gdown.download(url1, 'dengue.csv', quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1F-faNnQoyhdjbuyEVZPHV1cv_h0h5UDl
From (redirected): https://drive.google.com/uc?id=1F-faNnQoyhdjbuyEVZPHV1cv_h0h5UDl&confirm=t&uuid=8ffd95e6-3b8e-4c30-9ab9-b501250e66a0
To: /content/dengue.csv
100%|██████████| 168M/168M [00:00<00:00, 221MB/s]

'dengue.csv'

In [ ]:
# Read the CSV file into a DataFrame
df_dengue1 = pd.read_csv('dengue.csv')
df_dengue1

<ipython-input-6-7841d1420344>:2: DtypeWarning: Columns (22,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df_dengue1 = pd.read_csv('dengue.csv')

,OBJECTID,NO_KES,TRK_NOTI,TRK_DAFTAR,STATUS_XY,RUNSISDATE,OBJECTID_1,NO_NOTI,NO_KES_1,TRK_ONSET,...,TRK_RAWATA,TRK_DIAGNO,TPT_RAWATA,TRK_PTP,TRK_SRT,TRK_ULV,STATUS_PEN,STATUS_LOK,UJIAN_RAPI,RUNSISDA_1
0,1,2016/246923,2014/12/22,2014/12/28,Dalam Sempadan,2022/09/09,192,2221161,2016/246923,2014/12/19,...,NaN,2014/12/22,KLINIK KERAJAAN,NaN,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,TIADA,2022/08/19
1,2,2016/247869,2014/12/20,2014/12/28,Dalam Sempadan,2022/09/09,129,2218637,2016/247869,2014/12/16,...,2014/12/20,2014/12/20,WAD - HOSPITAL KERAJAAN,2014/12/24,2014/12/23,2014/12/23,KKM,Luar Bandar,TIADA,2022/08/19
2,3,2016/247870,2014/12/22,2014/12/28,Dalam Sempadan,2022/09/09,113,2219970,2016/247870,2014/12/20,...,2014/12/21,2014/12/22,WAD - HOSPITAL KERAJAAN,2014/12/24,2014/12/23,2014/12/23,KKM,Luar Bandar,TIADA,2022/08/19
3,6,2016/248203,2014/12/25,2014/12/28,Dalam Sempadan,2022/09/09,161,2224608,2016/248203,2014/12/15,...,2014/12/15,2014/12/25,WAD - HOSPITAL KERAJAAN,NaN,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,TIADA,2022/08/19
4,7,2016/248205,2014/12/25,2014/12/28,Dalam Sempadan,2022/09/09,18,2224730,2016/248205,2014/12/19,...,2014/12/23,2014/12/23,JABATAN KECEMASAN & TRAUMA (A&E) - HOSPITAL KE...,NaN,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,TIADA,2022/08/19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294003,527065,2022/3556,2022/02/03,2022/02/04,Dalam Sempadan,2022/09/09,546394,7700384,2022/3556,2022/01/30,...,NaN,2022/02/03,KLINIK KERAJAAN,2022/02/07,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,"NS1 Positif, IgG Negatif, IgM Negatif",2022/08/29
294004,527066,2022/3557,2022/02/02,2022/02/04,Dalam Sempadan,2022/09/09,546432,7699146,2022/3557,2022/01/31,...,2022/02/02,2022/02/02,JABATAN KECEMASAN & TRAUMA (A&E) - HOSPITAL SW...,2022/02/07,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,IgG Positif,2022/08/29
294005,527067,2022/3560,2022/02/03,2022/02/04,Dalam Sempadan,2022/09/09,546406,7693895,2022/3560,2022/02/02,...,2022/02/02,2022/02/03,JABATAN KECEMASAN & TRAUMA (A&E) - HOSPITAL SW...,NaN,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,NS1 Positif,2022/08/29
294006,527068,2022/3561,2022/02/03,2022/02/04,Dalam Sempadan,2022/09/09,546437,7698916,2022/3561,2022/01/31,...,NaN,2022/02/03,KLINIK KERAJAAN,2022/02/05,NaN,NaN,Pihak Berkuasa Tempatan,Bandar,IgG Positif,2022/08/29
294007,527075,2022/3568,2022/02/04,2022/02/04,Dalam Sempadan,2022/09/09,546452,7704847,2022/3568,2022/02/02,...,NaN,2022/02/04,KLINIK KERAJAAN,2022/02/05,2022/02/06,NaN,Pihak Berkuasa Tempatan,Bandar,"NS1 Positif, IgG Negatif, IgM Negatif",2022/08/29

In [ ]:
# insert file_id
file_id2 = '101YUU3obMz_qlsrPLk3TrCreMvcLaMEx'
url2 = f'https://drive.google.com/uc?id={file_id2}'

# Download the XLSX file
gdown.download(url2, 'data 2014.xlsx', quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=101YUU3obMz_qlsrPLk3TrCreMvcLaMEx
From (redirected): https://drive.google.com/uc?id=101YUU3obMz_qlsrPLk3TrCreMvcLaMEx&confirm=t&uuid=71449ca1-e299-4d49-8df5-29f221372a4e
To: /content/data 2014.xlsx
100%|██████████| 125M/125M [00:02<00:00, 50.7MB/s]

'data 2014.xlsx'

In [ ]:
# Read the XLSX file into a DataFrame
df_dengue2 = pd.read_excel('data 2014.xlsx', sheet_name = "MAIN DATA", dtype={'Rapid Test - Tkh Ujian Keputusan': str})
df_dengue2

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU16060 is marked as a date but the serial value 121000117000 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU17139 is marked as a date but the serial value 127000139000 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU20997 is marked as a date but the serial value 276000253000 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU21322 is marked as a date but the serial value 1.80000166000159e+17 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU51085 is marked as a date but the serial value 900526035915 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU59258 is marked as a date but the serial value 9000079000 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:223: UserWarning: Cell EU89343 is marked as a date but the serial value 80305101914 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

,Row_Num,Status Kawasan Keutamaan,Syarat Daftar Kes (Ujian/Klinika),Tanda-tanda Klinikal,Notifikasi no,Pesakit No,Epid Tahun (Tkh Input Notifikasi),Epid Minggu (Tkh Input Notifikasi),Epid Tahun (Tkh Notifikasi),Epid Minggu (Tkh Notifikasi),...,Status Tindakan Mahkamah,No. Rujukan Mahkamah,Tarikh Batal Tindakan Mahkamah,Ulasan,Tarikh Izin Dakwa TPR,Tarikh Daftar Kes,Tarikh Sebutan,Keputusan Kes,Kukuman Pengakuan,Nilai Denda (RM)
0,1,NaN,Y,Y,1788764,1788764,0,0,2014,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,Y,Y,1787269,1787269,2013,52,2013,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,Y,Y,1784100,1784100,2013,52,2013,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,3.0,Y,Y,1789081,1789081,0,0,2014,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4.0,Y,Y,1788543,1788543,2013,52,2013,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108693,108694,3.0,Y,Y,2228049,2228013,2014,53,2014,53,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108694,108695,NaN,Y,Y,2235087,2235051,2014,53,2014,53,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108695,108696,2.0,Y,Y,2231995,2231959,2014,53,2014,53,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108696,108697,4.0,Y,Y,2234921,2234885,2014,53,2014,53,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108697,108698,3.0,Y,Y,2233816,2233780,2014,53,2014,53,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# concatenate (stack dataframes vertically, and fill missing values with NaN)
df_dengue_concat = pd.concat([df_dengue1, df_dengue2], ignore_index = True)
df_dengue_concat

,OBJECTID,NO_KES,TRK_NOTI,TRK_DAFTAR,STATUS_XY,RUNSISDATE,OBJECTID_1,NO_NOTI,NO_KES_1,TRK_ONSET,...,Status Tindakan Mahkamah,No. Rujukan Mahkamah,Tarikh Batal Tindakan Mahkamah,Ulasan,Tarikh Izin Dakwa TPR,Tarikh Daftar Kes,Tarikh Sebutan,Keputusan Kes,Kukuman Pengakuan,Nilai Denda (RM)
0,1.0,2016/246923,2014/12/22,2014/12/28,Dalam Sempadan,2022/09/09,192.0,2221161.0,2016/246923,2014/12/19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,2016/247869,2014/12/20,2014/12/28,Dalam Sempadan,2022/09/09,129.0,2218637.0,2016/247869,2014/12/16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,2016/247870,2014/12/22,2014/12/28,Dalam Sempadan,2022/09/09,113.0,2219970.0,2016/247870,2014/12/20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6.0,2016/248203,2014/12/25,2014/12/28,Dalam Sempadan,2022/09/09,161.0,2224608.0,2016/248203,2014/12/15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7.0,2016/248205,2014/12/25,2014/12/28,Dalam Sempadan,2022/09/09,18.0,2224730.0,2016/248205,2014/12/19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tidak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(df_dengue1)

294008

In [ ]:
len(df_dengue2)

108698

In [ ]:
len(df_dengue1)+len(df_dengue2)

402706

In [ ]:
df_dengue_concat.to_csv("df_dengue_concat.csv")

from google.colab import files
files.download("df_dengue_concat.csv")